---
name: Run zenload
author: Stefan Aeschbacher
description: runs zenload for 5 seconds with a cpu test
architecture: linux
services:
  zenload:
    image: saeschbacher/zenload
    setup-commands:
      - sleep 20

flow:
  - name: CPU-Load
    container: zenload-container
    commands:
      - type: console
        command: zenload -v -c 5
        note: Starting zenload
