---
name: Run zenload
author: Stefan Aeschbacher
description: runs zenload for 5 seconds with a cpu test
architecture: linux
services:
  zenload-container:
    image: saeschbacher/zenload
    setup-commands:
      - sleep 20
    volumes:
      - ./zenario.yml:/zenario.yml

flow:
  - name: CPU-Load
    container: zenload-container
    commands:
      - type: console
        command: zenload -f /zenario.yml
        note: Starting zenload
